訂正しました
shatoo1551/laravel_news8 pull request #2
Opened 2021-01-20 13:04 UTC by shatoo1551

2021-01-21 14:45 UTC, shatoo1551 commented
メンターさん、コメントはここに表示されるのでしょうか？

2021-01-22 00:04 UTC, Shibata0806 commented on index.php
> +        if( empty($_POST['title'])  || empty($_POST['text'])) {
要件として、以下があります。
```
"タイトル" …  必須 かつ 30文字以下
"記事"  …  必須
```
「30文字以下」が満たされていないようですので、こちらの対応をお願いします。

2021-01-22 00:08 UTC, Shibata0806 commented on index.php
> +            $error_message[] = '表示名を入力してください。';
せっかく`$error_message[]`という配列に「表示名を入力してください」というメッセージを格納しているので、画面上のエラーメッセージにも利用できるように実装すると、ベターですね。

2021-01-22 00:22 UTC, deel1931 commented on index.php
> +        .post{
cssは別ファイルの方の方がコードが読みやすくなるのでcssは分けて書いてみてください。

2021-01-22 00:22 UTC, deel1931 commented on dbc(myadmin).php
> +
要件に満たない不要なファイルは基本的にプルリクエストには出さないようにした方が良いので次回から意識してみてください！

2021-01-22 00:22 UTC, deel1931 commented on index.php
> +        // トータルページ数※ceilは小数点を切り捨てる関数
javascriptもcss同様に分けて書いてください。

2021-01-22 00:22 UTC, deel1931 commented on detail.php
> +    <style>
cssは分けて書いてみてください。

2021-01-22 00:24 UTC, Shibata0806 commented on index.php
> +            $_SESSION['success_message'] = 'メッセージを書き込みました。';
ここでセッションにメッセージを入れていますが、このあと使っていないようですので、この行はない方がよいと思います。今回は、ただ不要な処理ですが、セッションに不用意に値を入れると思わぬバグに繋がることがありますので、セッションを利用する際にはご注意ください。

2021-01-22 01:05 UTC, Shibata0806 commented on index.php
> +            <a href="delete.php?i=<?php echo $count-$i ?> ">削除</a><br><br>
「記事の削除」機能は、要件に含まれていないので、いらなかったですね。

せっかく作っていただいていたので、コメントさせていただきます。

永田さんの場合、記事を識別するIDとしてファイル内に何行のデータがあるかのcountを用いていると思います。この場合、記事を追加したり削除したりすると、その時点のcountがその場面場面で上下します。（イメージ伝わりますでしょうか。）

すると、コメント用のデータは、記事のIDに紐づけていると思うので、削除した記事のIDが再度登場してしまい、削除した記事のコメントが新たな記事に紐づいてしまうことになります。

なので、記事自体を削除する機能を実装する場合には、一度使った記事のIDは二度と使われないように実装しなけばならないですね。

例えば、PHPにはユニークな文字列を生成する関数を使って他のIDと重複しないようにするなどの方法が挙げられます。

2021-01-22 01:07 UTC, Shibata0806 commented on index.php
> +            $alert = "<script type='text/javascript'>alert('入力してください');</script>";
課題の要件としては、アラートではなく、HTML上にメッセージとして表示しているので、その見た目に合わせましょう。

2021-01-22 01:17 UTC, Shibata0806 commented on index.php
> +?>
ここは、ページングをしようとしてる処理でしょうか。
画面上にこれに関係する情報を見つけられず、もし不要な物でしたら削除しましょうか。
認識間違ってたら教えてください。

2021-01-22 01:25 UTC, Shibata0806 commented on detail.php
> +    }
このIF分に入ることはないのではないでしょうか。
不要そうでしたら削除しましょう。

2021-01-22 01:26 UTC, Shibata0806 commented on detail.php
> +            $alert = "<script type='text/javascript'>alert('入力してください');</script>";
課題の要件としては、アラートではなく、HTML上にエラーメッセージを出しているので、そのように実装しましょう。

2021-01-22 01:30 UTC, Shibata0806 commented on detail.php
> +	<?php unset($_SESSION['success_message']); ?>
投稿に成功しても、「メッセージを書き込みました。」っていう文言が画面上に表示されないですね。

デバックしてもよいですが、今回の要件には含まれていないので、削除してもよいと思います。削除する場合、上の方にある`$_SESSION['success_message']`も不要になるので合わせて削除しましょう。

2021-01-22 01:33 UTC, Shibata0806 commented on delete_comment.php
> +</html>
このHTMLが表示されることは、ないのではないでしょうか。

2021-01-22 01:34 UTC, Shibata0806 commented on delete.php
> +</html>
このHTMLが表示されることはないのではないでしょうか。
不要でしたら、削除しましょう。

2021-01-22 01:39 UTC, Shibata0806 commented on detail.php
> +                    <form type="post" ><a href="delete_comment.php?i=<?php echo $count -$ii  ?>&id=<?php echo $i  ?>">削除<a></form>
aタグのリンクはGETになります。
GETとPOSTの使い分けは以下のようになります。
GET・・・サーバーから情報を取得して表示させる処理に使う
POST・・・サーバーに情報を与えて何らかの処理に実行させる

今回は、「サーバーにコメントの番号を伝えて、該当のコメントをdeleteする処理を実行する」なので、POSTでsubmitする方がベターですね。
POSTにする場合、`delete_comment.php`もPOSTで受け取るように修正する必要があります。

2021-01-22 01:40 UTC, Shibata0806 commented on index.php
> +            <a href="delete.php?i=<?php echo $count-$i ?> ">削除</a><br><br>
あと、aタグのリンクはGETになります。

「サーバーに記事の番号を伝えて、該当の記事をdeleteする処理を実行する」なので、POSTでsubmitする方がベターですね。
POSTにする場合、`delete.php`もPOSTで受け取るように修正する必要があります。

2021-01-22 01:46 UTC, Shibata0806 requested changes
@shatoo1551 さん

コメントしました。

全体的な所感としては、課題の完了が早かったこと、しっかり実装ができていることが素晴らしかったと思います！

今後の改善としては、
・要件の内容とずれているところがあるので、しっかり要件に沿った形で実装をする。
・ソースコードに不要な処理が含まれていないか確認して、不要なソースは削除する
・不要なコメントアウトがたくさん見受けられるので、極力減らす
などでしょうか。

レビューをする際に、レビュアーが見るコード量が多くなると、その分負担も増えてきます。
今後、チーム開発する際に、相手の仕事の負担を減らしてあげるために、見やすいコードを書くことも重要なスキルになってきます。今はまだプログラミングを始めたばかりですが、今後少し意識しながらコードを書いていってみてください！

2021-01-22 05:54 UTC, shatoo1551 commented on index.php
> +?>
ページング処理の途中です！
これからやろうと思っています。

2021-01-22 05:55 UTC, shatoo1551 commented on delete_comment.php
> +</html>
ここは遷移した後にどのようにget が値を受け取ってるかを確認するページでした。消しときます。

2021-01-22 05:56 UTC, shatoo1551 commented on delete.php
> +</html>
ここも、上のものと同じですね。消しときます。

2021-01-22 05:58 UTC, shatoo1551 commented
柴田さん、大変細かなレビューありがとうござました！作ったものをすぐあげただけなので、ゴミがたくさん落ちてます！見にくくてすみません。これからは、完璧な状態で遅らせていただきます。これからもよろしくお願いします！

2021-01-22 12:48 UTC, Shibata0806 commented
@shatoo1551 
はい、これからも頑張ってください！よろしくお願いいたします。

今回の課題は、講師1人からApprove（承認）してもらうことが条件となっています。
GithubのApproveについては、以下をご参考にして下さい。
https://qiita.com/YumaInaura/items/8223add6d8335a2eda7f

なので、指摘があった箇所で修正すべきところは、同じブランチで修正していただき、git pushしていただけますでしょうか？
作業や流れのイメージがつかない場合はご質問ください。


また、他の方のGithubのレビューも上がってきていますので、もしよかったら柳沢先生のレビューものぞいてみてください。
人によってコードの書き方が違ったり、レビュアーによって着眼点が違ったりなど、とても参考になることで溢れています。

より確実に動作して、他人が理解しやすいコードが書けて、レビュアーとしても的確な着眼を持てることが、より良いエンジニアに成長できる一つの要素です。ぜひ、時間をかけて取り組んでみてください。

2021-02-04 23:03 UTC, merged